services:
  - type: web
    name: freshmart-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: freshmart-db
          property: connectionString

databases:
  - name: freshmart-db
    databaseName: grocery_ecommerce
    plan: free
